---
- name: Install java and net-tools
  hosts: ubuntu
  become: yes
  tasks:
   - name: Update apt repo and cache
     apt: update_cache=true force_apt_get=true cache_valid_time=3600
   - name: Install java 8 
     apt: name=openjdk-8-jre-headless state=present
   - name: Install net-tools
     apt:
       name: net-tools
       state: present

- name: Download and unpack Nexus Installer
  hosts: ubuntu
  become: yes
  tasks:
   - name: Download 

  
