---
- name: Install java and net-tools
  hosts: ubuntu
  become: yes
  tasks:
   - name: Update apt repo and cache
     apt: update_cache=true force_apt_get=true cache_valid_time=3600
   - name: Install java 8 
     apt: name=openjdk-8-jre-headless state=present
   - name: Install net-tools
     apt:
       name: net-tools
       state: present

- name: Download and unpack Nexus Installer
  hosts: ubuntu
  become: yes
  tasks:
   - name: Check if nexus folder already exists
     stat:
       path: /opt/nexus
     register: stat_result
   - name: Download Nexus
     get_url: 
       url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
       dest: /opt
     register: download_result
   - name: Unpack Nexus tar-archive
     unarchive:
       src: "{{ download_result.dest }}"
       dest: /opt/
       remote_src: yes
     when: not stat_result.stat.exists 
   - name: Fing Nexus folder
     find: 
       paths: /opt
       pattern: "nexus-*"
       file_type: directory
       use_regex: false
     register: find_result
   - name: Rename defaul nexus folder
     shell: mv {{ find_result.files[0].path }} /opt/nexus
     when: not stat_result.stat.exists

- name: Create new user Nexus to own nexus folder
  hosts: ubuntu
  become: yes
  tasks:
   - name: Ensure group nexus already exists
     group:
       name: nexus
       state: present
   - name: Create new user nexus
     user:
       name: nexus
       group: nexus
   - name: Make nexus user owner of nexus folder
     file: 
       path: /opt/nexus
       state: directory
       owner: nexus
       group: nexus
       recurse: true
   - name: Make	nexus user owner of sonatype-work folder
     file: 
       path: /opt/sonatype-work
       state: directory
       owner: nexus
       group: nexus
       recurse: true

- name: Start nexus with nexus user
  hosts: ubuntu
  become: yes
  become_user: nexus
  tasks:
   - name: Set run_as_user in nexus config
     lineinfile: 
       path: /opt/nexus/bin/nexus.rc
       regexp: '^run_as_user=""'
       line: run_as_user="nexus"
   - name: Start Nexus
     command: /opt/nexus/bin/nexus start
