---
- name: Install java and net-tools
  hosts: ubuntu
  become: yes
  tasks:
   - name: Update apt repo and cache
     apt: update_cache=true force_apt_get=true cache_valid_time=3600
   - name: Install java 8 
     apt: name=openjdk-8-jre-headless state=present
   - name: Install net-tools
     apt:
       name: net-tools
       state: present

- name: Download and unpack Nexus Installer
  hosts: ubuntu
  become: yes
  tasks:
   - name: Download Nexus
     get_url: 
       url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
       dest: /opt
     register: download_result
   - name: Unpack Nexus tar-archive
     unarchive:
       src: "{{ download_result.dest }}"
       dest: /opt/
       remote_src: yes 
   - name: Fing Nexus folder
     find: 
       paths: /opt
       pattern: "nexus-*"
       file_type: directory
       use_regex: false
     register: find_result
   - debug: msg={{find_result}}
 

  
